package com.english.words;

/**
 * 初始化单词数据
 * @author Wizen
 *
 */
public class Words {

	//单词表
	public static final String [] wordsArray={
		"academia n. 学术界,acumen n. 敏锐，聪明,ambiguous adj. 不明确的,ambiguity n. 不明确,brink n. 始发点,collaborative adj.协作的合作的,collaborator n.合作者,contributor n.投稿人,conviction n.坚定的信仰,expertise n.专门知识,foster v.培养，促进,headhunter n.猎头,lone wolf n.自行其是的人,mindset n.思维定式,mitigate v.缓和,mobilize v.争取支持,newbie n.新手,outshine v.优于,perception n.看法认识,prioritize v.使。。优先,prospective adj.预测的，未来的,scary  adj.可怕的,studied adj.经过深思熟虑的,teamwork n.合作，协作,transition n.过渡，转变,act on 按。。。行事,count on 指望,in pursuit of  追求,make up 编造,pep talk 鼓舞士气的讲话,place a bet下赌注,put one's neck on the line 冒险,stick one's neck out 说冒险的话,stand out 突出，显眼,",
		"adherence n.坚持，信守,affirm v.肯定，强化,autonomy n.自主能力,blockhead n.笨蛋，蠢人,brief n.案情摘要,civility n.礼貌，客气,cost effectivecivility n.礼貌，客气,cut-rate adj.减价销售的,cynical adj.愤世嫉俗的,dealing n.商业活动,discourse n.谈话交谈,due adj.应给的，欠下的,eminent adj.著名的，有名望的,empower v.给做。。。。的权利,encompass v.包含,equitable adj.公平合理的,equity n.普通股，股票,ethical adj.合乎道德的，正确的,gratify v.感到高兴和满意的,gratification n.高兴满足,inculcate v.灌输,in-house adj.内部的,internalize v.内在化,intertwine v.密切相关的,kowtow v.顺从巴结,milestone n.里程碑,neurosis n.神经官能症,outlive  比。。。经久,outperform v.做的比。。。好,prospective adj.预测的，未来的,pro bono adj.为了公益的,professionalism n.专业技巧,promulgate v.公布颁布,promulgation n.公布颁布,psychic adj.精神上的,rigor n.严酷，艰苦,sanity n.明智，清醒,subsume v.把。。。归入某一类,superlative adj.最优秀的最好的,taxation n.征税收税,top-flight adj.最成功的,venue n.举行场所，会场,by definition 从定义上讲,commit oneself to doing sth. 答应，承诺,for its own sake 为获得做某事的经历,impinge on 对。。。起作用,in the short term 短期而言,in this regard 关于此事,slake one's thirst满足（欲望）,take precedence 优先于,thirst for渴望，渴求,with reference to 关于,",
		"aftertaste n.余味,apportion v.分配分摊,apprentice n.学徒,broth n.肉汤，米汤,ceramic adj.陶瓷的,chili pepper n.辣椒粉,chrysanthemum n.菊花,collective adj.集体的，共同的,commemorate v.纪念，庆祝,culinary adj.烹饪用的,drainage n.排水，排污,dynasty n.朝，代,eccentric adj.怪异的，古怪,exquisite  精致的,facet n.一个方面,fare n.食物,ferment v.使。。。发酵,filling n.馅,fragrance n.香味,garnish n.装饰菜,ginger n.姜,glutinous adj.很黏的,greasy  adj.多脂的,harmonious adj.和睦的，融洽的,humility n.谦逊，谦恭,improvise v.即席而作,light adj.味道清淡的,lingering adj.经久不消的,literally adv.逐字地,longevity n.长寿,maw n.动物的嘴,precept n.戒律，准则,reed n.芦苇,reign n.统治时期,renowned adj.著名的,scallop n.扇贝,seniority n.年长的，职位高的,specialty n.特色菜,stew  v.炖，焖,tendon n.腱,toast n.祝酒,triangular adj.三角形的,whiff n.一阵气味,bid fare well to告别,make a fool of oneself  出丑,partake of   吃喝,urge...on  激励人,",
		"albeit conj.虽然，尽管,bass  n.鲈鱼,bistro  n.小餐馆,boar  n.野猪,Brie  n.布里奶酪,congenial adj.宜人的,edict  n.法令,emblematic adj.象征性的,ensnarl  v.使被纠缠,exceptional adj.非常好，杰出的,exceptionalism n.异常优越,fiscal  adj.财政的,fishmonger  n.鱼贩,Gallic adj.法国的,greengrocer n.蔬菜水果商,haricot  n.菜豆，扁豆,hub  n.中心，枢纽,impudent adj.无礼的,infamous adj.声名狼藉的,kiwi n.猕猴桃,mediocre adj.平庸的，平凡的,meringue n.蛋白酥,oyster n.牡蛎,plague v.折磨,quaint adj.奇特的，古色古香的,quaintness n.奇特,regime n.政体,restaurateur n.餐馆老板,restive  adj.焦躁不安的,rugby n.橄榄球,savor  v.品尝,skeptical adj.持怀疑态度的,stopgap  n.补缺者,stymie v.阻碍，妨碍,subsidy n.补偿金,venison  n.鹿肉,bite the dust死亡，失败,draw on  利用，凭,fight a rearguard action   竭尽全力,red ink  赤字,red tape繁琐费时的手续,take effect   开始起作用,tax break  减税优惠,",
		"advance n.预先的，提前的,affectionately adv.亲切地，有感情地,annotate v.加注解于,articulate v.清楚地表达，清晰地吐（字）,banish v.驱逐，赶走,bereavement n.丧亲（之痛），丧友（之痛）,cataclysmic adj.剧变的，骤变的,conservative adj.保守的,conservatively adv.保守地,cop n.警察,craft v.精制,defenseless adj.未设防的，无防备的,deftly adv.灵巧地，敏捷地,derivative adj.无独创性的，无新意的,earmark n.特征,enticing adj.吸引人的,fledgling adj.新生的，年轻的,fundamentalist n.信奉正统基督教的人,goblet n.无柄高脚杯,hedge v.避免作出正面回答，规避,installment n.部分，分册,intellectualism n.理智,magisterial adj.权威的，威严的,maturity n.成熟,note n.口气，调子,orphan n.孤儿,outdo v.超过，胜过,outright adj.完全的，彻底的,plotline n.情节主线，主要情节,promise v.有、、、的希望,prose n.散文,punch n.宾治，潘趣酒,quibble n.小小的不满，吹毛求疵,quirky adj.古怪的，奇特的,resistible adj.可抵抗的，可抵制的,seductive adj.诱人的，有魅力的,sour adj.敌对的，不愉快的,unadorned adj.未装饰的，不加渲染的,undercurrent n.潜伏的情绪,villain n.坏人，反面角色,witchcraft n.巫术,wizard n.男巫,amount to 等于，相当于,chop off 去掉，砍掉,keep clear of 避开，免于,pick up on 觉察，明白,pull off 赢得，努力实现,put it mildly 说的委婉些，毫不夸张的说,stack up  比较，比高低,strike a chord 引起某人的共鸣,the likes of 那样的,there's no telling 很难说，无法预料,thrust sth. on sb把。。。强加于,",
		"amphitheater n.圆形剧场,bacchanal n.纵酒的欢宴,confines n.界限，范围,drop-dead gorgeous adj.非常吸引人的,fascism n.法西斯主义,festivity n.欢庆，欢乐,gregarious adj.爱交际的，不喜欢独处的,hedonism n.享乐主义,impromptu adj.即兴的,intrinsic adj.固有的，本质的,jam-packed adj.非常拥挤的,makeshift adj.临时的,melancholy adj.忧郁的，令人感伤的,merengue n.梅仑格舞,multiethnic adj.多民族的,Protestant n.新教徒,puritanical adj.清教徒似的,quiche n.什锦烘饼,repressive adj.压抑的，抑制的,salsa n.萨尔萨舞,small-town adj.狭隘的,sneer n.冷笑，嘲笑,stroll n.散步，闲逛,tango n.探戈舞,trek n.长途艰辛旅行,unhinge v.使、、、发狂,unprecedented adj.前所未有的,zeal n.热情，热忱,a staple of 重要部分,be packed with 充满，到处都是,bump into 偶然碰见，遇见,catch on 流行起来,descend on 突然来访,in any event 无论如何,loosen up 放松，无拘无束,mull over 反复思考,stumble across 偶然发现,take up 开始花时间从事,the small hours 凌晨时分,throw oneself into 积极投身于,tuck into 痛快地吃,",
		"accommodate v.迎合，迁就,altruistic adj.无私的,avalanche n.雪崩,bolster v.改进,cuddle v.拥抱,elusive adj.难以表述的,frenzied adj.疯狂的,impair v.削弱，损害,impairment n.削弱，损害,liaison n.密切的联系，关系,mundane adj.平淡的，平凡的,myriad adj.无数的,neurotic adj.神经质的神经过敏的,obsessive adj.着迷的,physiological adj.生理系统的,platonic adj.纯友的,prerequisite n.必备条件,psychosomatic adj.由精神压力引起的,reminisce v.缅怀往事,retard v.阻碍，减缓,retardation n.阻碍，减缓,witticism n.妙语，俏皮话,wry adj.苦笑的,culminate in 最终达到,deprive sb. of sth. 剥夺,filter out 过滤，滤除,",
		"courtship n.恋爱期,debilitating adj.虚弱的,dementia n.痴呆,devise v.想出，设计,hindsight n.后见之明,litany n.后见之明,rickety n.反复的赘述,truce adj.摇摇晃晃的,be at each other's throats 相互斗嘴,launch into 突然开始,lavish sth. on sb. 过分慷慨的给予,make the best of sth. 尽可能善用,reel sth. off 滔滔不绝的重复,take shape 形成,whittle away 削减，削弱,",
		"adept adj.熟练地,adherent  n.信徒，拥护者,align v.使。。。排成一线,artifact n.手工艺品,cardiologist n.心脏病专家,disciplined adj.受过训练的,hypertension n.高血压,indicator n.指示物,innovator n.创新者,meditation n.默念，默想，冥想，打坐,nominal adj.（金额）极小的，微不足道的，象征性的,posture n.姿势，体态,practitioner n.（某种活动的）从事着，实践者,prestigious adj.有声望的，有威望的,prevalent adj.流行的，普遍的,prop n.支柱，支撑物,reimburse v.偿还,reiterate v.反复地说，重申,sedentary adj.（工作等）坐着做的，案头的,stamina n.持久力，耐力，毅力,strenuous adj.艰苦的，要花功夫的,tout v.再养，吹捧,well-being n.舒适，健康；幸福,yogi n.瑜伽师，瑜伽教授者,",
		"adaptation n.适应,ambiguous adj.暧昧的，不明确的,chronic adj.（问题）长期的，反复出现的,cognitive n.认知的，认识过程的,compromise v.危及，损害,hassle n.麻烦,irritation n.令人气恼的食物,juggle.（尤指艰难地）兼顾,magnitude n.巨大，庞大，重要性,overload n.超载,severe adj.严重的,severity n.严重程度，严重性,squabble v.吵嘴,stressor n.带来压力的因素,terrain n.地形，地势,turmoil n.骚乱，混乱,understaffed adj.人员不足的，人手不足的,fit into 属于,stress out （使）非常紧张疲惫,",
		"arena n.表演场地,bestow v.给予，赠给,bolero n.敝胸短上衣,clown v.扮小丑，胡闹,compact adj.小而紧凑的,conserve v.保存，保护,convention n.会议，大会,cornice n.上楣，飞檐,deed n.行为，行动,deficiency n.缺乏，不足,distraction n.使人分心的事物,dubious adj.疑惑的,ebb n.退潮，落潮,editorial n.社论,emanation n.散发物，发射物,enact v.上演,evangelist n.巡回布道者,exalted adj.高贵的，尊贵的,excess n.过分，过量,execute v.将、、、处死,exotic adj.外来的，外国的,fit n.一阵发作,forgo v.摒绝，放弃,forlorn adj.孤苦伶仃的,forlornness n.孤独，凄凉,forsake v.遗弃，抛弃,forsakenness n.被抛弃,gladiator n.角斗士,grail n.梦寐以求的东西,impart v.赋予，给予,inflict v.使承受，遭受,insulate v.隔离，使隔绝,lapel n.翻领,largess n.慷慨赠予的钱或礼物,liner n.客轮,Lion n.要人，名人,metropolis n.首要城市，大都会,miasmic adj.煤气扑鼻的,morale n.士气，斗志,overwhelming adj.压倒一切的,penetrating adj.弥漫的，渗透的,queer adj.奇怪的，难以解释的,rejuvenate v.使变得年轻,rejuvenation n.返老还童,sanctuary n.避难所，庇护所,siren n.汽笛，警报器,sloop n.单桅小帆船,somewise adv.以某种方式,spectacle n.奇观，壮观景象,splashy adj.显眼的,stifling adj.闷热的,stimulus n.刺激，刺激物,sustenance n.食物，营养,tack v.使转变航向,expunge v.删除，除去,unexpungeable adj.无法抹去的,undertaking n.任务，事业,unresourceful adj.无法解决的,usher v.接入，接待,vibrations n.感应，共鸣,waterfront n.水边土地,weatbound n.向西行的,account for 是、、、的原因,at any rate 无论如何,be content with 满足于,come along 出现，发生,for that matter 对、、、同样如此,lie in state 供瞻仰,pull up stakes 搬家,sweat out 坚持做完,tune out 置之不理,",
		"adore v.爱慕,afar adv.遥远的,assortment n.各式各样的混合物,ballerina n.芭蕾舞女演员,bang n.刘海,belch v.打嗝,blink v.眨眼,clump n.丛，簇，群,coo v.低声细语,crinkly adj.硬而卷曲的,dainty adj.优美的，小巧的,deck n.一副,eyebrow n.眉毛,Formica n.福米加塑料面膜,fuzz n.细毛，茸毛,hight-pitched adj.声调高的,indignity n.轻蔑，侮辱,manger n.食槽,poke v.戳，捅,prodigy n.奇才，天才,purse v.撅起嘴唇,reproach n.责备，指责,slant n.倾斜,soggy adj.湿透的,sparkly adj.有生气的，有活力的,sulk v.生闷气,tiptoe n.脚尖，指尖,uneven adj.不规则的,vendor n.小贩,willfull adj.任性的,for good 永远,look down on 轻视，瞧不起,lop off 砍掉,",
		"acorn  n.橡树果,alteration  n.变动，改变,antiquity  n.古代,battlefront  n.前线,covet v.觊觎，垂涎，贪求,desecrate v.亵渎,deviate v.背离，偏离,disposition  n.性情，性格,endeavor  v.尝试，努力,engross v.使非常感兴趣，使全神贯注于,germinal adj.初级阶段的，处于萌芽状态的,germinally adv.初级阶段地，处于萌芽状态地,home-front  n.大后方,humanitarian  n.人道主义者,indestructible adj.不可摧毁的，坚不可摧的,knavish  adj.无赖似的，人品不正的,matrix  n.发源地，摇篮,miser  n.守财奴，吝啬鬼,mosaic  n.镶嵌画般的东西,obliterate v.忘却，抺去,philanthropist  n.慈善家，乐善好施者,preacher  n.说教者，讲道者,proverbial  adj.众所周知的,temperament n.气质，性情，性格,traitor  n.叛徒，背叛者,defile v.污损，污染，亵渎,undefiled  adj.未沾污的，纯洁的，纯粹的,unfold  v.展现，逐渐呈现,unsavory adj.令人不快的，令人厌恶的,be a far cry from  与。。。大不相同,at the peril of 冒着丧失（或伤害）。。。的危险,be in order 适宜，合适,hold to （使）遵循，坚持,",
		"aghast adj.大为震惊的，吓呆了的,arcade n.拱廊,beak  n.鸟嘴，喙,bum  n.流浪乞丐,buzzard  n.兀鹰,censure  n.严厉谴责，声讨,defer v.延期，推迟,ebony  adj.乌黑的,elude  v.使记不起来，把。。难倒,exasperate v.使恼怒，使烦恼,flick v.弹去，拂去,frequent  v.常去，常到,gleam  n.隐现，闪现,grimy  adj.满是污垢的，蒙上灰尘的,interminable adj.冗长乏味的,ivory  adj.象牙色的，乳白色的,jangle v.发出噪音,macaroni n.通心面，通心粉,motley  adj.形形色色的,piteous adj.可怜的，让人怜悯的,recollection  n.记起，想起,resentment n.愤恨，不满，憎恶,resounding adj.回响的，洪亮的,singlet n.无袖汗衫，运动背心,steadfast adj.忠实的，忠诚的,steadfastly  adv.忠实地，忠诚地,tatters  n.破旧衣服，破布,thong n.皮带子，梢,wane v.逐渐减弱,whack n.重击（声),wince  v.皱眉蹙眼（因疼痛或不安致面部表情突然改变）,wretched adj 不幸的，可怜的，苦恼的,wretchedness n 不幸，可怜，苦恼,on the tip of one's tongue 就在嘴边（但记不起来）,put in 进港,rack one's brain  绞尽脑汁,scrunch sth. up  把。。。。揉成一团,throw sb./sth. over  抛弃,to one's dismay  令某人沮丧的是,wear on （时间）慢慢地过去,",
		"benchmark  n.基准,benign  adj.无害的，良性的,daring adj.鲁莽的,daringly  adv.鲁莽地,emeritus adj.保留头衔而退休的，荣誉退休的,malign  adj.有害的,mandate v.命令，指示,maneuver  n.熟练的动作,mantra n.常用的老话,negotiate  v.顺利通过，成功越过,perverse adj.任性的，不合情理的，一意孤行的,reckless adj.轻率的，鲁莽的，不顾危险的,recklessly adv.轻率地，鲁莽地，不顾危险地,redistribute v.再分配，再分发,redistribution  n.再分配，再分发,skeptic  n.怀疑论者,sober  adj.未喝醉的，清醒的,stake  n.树桩,toddler  n.蹒跚学步的孩子,trapeze  n.杂技秋千,visceral  adj.内心深处的,at the mercy of  任由某人摆布,bang up  撞毁,black and white  是非分明的,be bound to   很有可能，肯定会,buckle up  系安全带,take sth. into account  考虑,tally up  计算,to boot  并且，加之,",
		"accommodate  v.容纳,astounding  adj.令人震惊的,autonomous  adj.独立的,autonomously  adv.独立地,back  v.支持，鼓励，资助,comprehensible  adj.易于理解的,congestion  n.拥挤，堵车,coverage  n.覆盖范围,crisp adj.清晰的,criss-cross  v.纵横交错,depository n.存放处,detector  n.探测器,implement v.使生效，贯彻，执行,inductance n.感应系数，自感应,infrared  adj.红外线的,infrastructure  n.基础设施,loop  n.回路，循环,marvel  n.奇迹，令人惊奇的人或物,obstruction  n.障碍物，阻碍物,be/come/arrive on the scene 到场，在场,integrate into/with  融入或成为一体,lay out 设计,spread out  伸展，延伸,with regard to  关于。。。。 ,work on  致力于,",
		"clog v.堵塞,cram v.把、、、塞入,crash v.借宿,demolish v.摧毁，拆掉,development n.新建住宅区,dire adj.极可怕的,divert v.改变,dole n.救济金,eligible adj.合格的,eliminate v.消除，根除,flatline v.降到很低的水平,hellhole n.地狱般的地方,initiative n.计划，措施,lot n.一块地,lousy adj.糟糕的,mismatch n.不匹配,mortgage n.抵押贷款,pending adj.未定的，待决的,raze v.把、、、夷为平地,skimp v.舍不得花,slump v.暴跌,soar v.骤升，猛增,stall v.停滞不前,status quo n.现状,subsidize v.给予补助,traction n.牵引力,virtually adv.实际上,voucher n.代金券，凭证,windfall n.意外之财,at one's disposal 供某人支配,be down on one's luck 穷困潦倒,revolve around sth. 以、、、为主题,tear sth. down 拆毁,make ends meet 收支平衡,",
		"appreciation n.增值,align v.与、、、结盟,analogous adj.类似的，相似的,congested adj.交通拥挤的,demographic n.特定的人群,dynamic n.活力,fervent adj.热情的，热烈的,froth n.泡沫,imposition n.实施，征收,incentive n.刺激，动力,municipality n.市，自治区,oxymoron n.矛盾修辞法,remodel v.重新塑造,renovation n.装饰，修复,scrimp v.尽量节省,zone v.划分成地区,in the short run 从短期看来,by the same token 由于同样的原因,",
		"catholic adj.广泛的，普遍的,collegial adj.大学的，学院的,consensus n.意见一致,contemplation n.深思,diffusion n.传播，散播,discernment n.洞察力，敏锐,disseminate v.传播，散播,eloquent adj.雄辩的,embryo n.胚胎,foremost adj.首要的，第一的,illumination n.阐明,immunize v.使免疫,impart v.传授，告知,imperative n.需要,inaugural adj.就职的，开始的,incubator n.孵化器,laureate n.获奖者,lavish adj.过分多的,lavishly adv.过分慷慨的,long-standing adj.长期存在的,non-partisan adj.无党派的,porous adj.可渗透的，多孔的,predecessor n.前辈，前任,rigor n.严密，谨慎,robustness n.健全，稳固,scholarly adj.学术性的,serendipity n.天赋,staggering adj.令人吃惊的,staggeringly adj.令人吃惊的,solitary adj.单独的，独自的,suffuse v.弥漫，充满,supersede v.代替，取代,underlie v.成为、、、的基础,utilitarian adj.功利的,vulnerable adj.脆弱的,vulnerability n.易受伤，脆弱,call on/upon sb. 呼吁，号召,couple...with... 并提，加上,live up to 符合，履行,",
		"brainpower n.智囊团，人才,burgeoning adj.迅速增长的,contender n.竞争者,counterpart n.对应的人或物,exacerbate v.使加剧,imperil v.危及,intensify v.加强，增强,lucrative adj.赚钱的,offset v.补偿，抵消,squander v.浪费，挥霍,stunning adj.令人印象深刻的,upshot n.结果,a recipe for sth. 是、、、的秘诀,brace oneself for sth. 使准备迎接,fall behind 落后,may well 极有可能,",
	
	};
}
